(define-module (wemacs init)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 pretty-print)
  #:use-module (wemacs browser)
  #:use-module (wemacs keymap)
  #:use-module (wemacs repl)
  #:use-module (wemacs events)
  #:export (init run-tests))

(define (run-tests)
  (pretty-print (all-threads))
  (current-thread))

(define (init)
  (if (file-exists?
  (add-hook! key-press-hook handle-key-press)
  (add-hook! key-press-hook debug-key-press)
  (add-hook! event-hook debug-event))

 ;; (repl-start)
 ;; (browser-start))
 ;;  (let ((t (begin-thread (repl-start) (browser-start))))
 ;;    (while #t (sleep 1))))
 ;; ;; (let ((t (make-thread (browser-start))))
 ;;   (repl-start)
 ;;    (join-thread t)))
