(define-module (nomad tests)
  #:use-module (nomad browser)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 pretty-print)
  #:export (run-tests))

(define (run-tests)
  (next-buffer)
  (sleep 3)
  (browse "https://www.gnu.org/s/guile")
  (sleep 3)
  (next-buffer)
  (sleep 3)
  (next-buffer)
  (pretty-print (all-threads))
  (current-thread))
