\input texinfo
@c -*- texinfo -*-

@c %**start of header
@setfilename nomad.info
@documentencoding UTF-8
@settitle Nomad Reference Manual
@documentlanguage en
@c %**end of header

@include version.texi

@include urls.texi

@copying
Copyright @copyright{} 2019 Amar M. Singh@*

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end quotation
@end copying

@dircategory Nomad
@direntry
* Nomad: (nomad).       Extensible self-documenting web browser.
@end direntry

@titlepage
@title Nomad Reference Manual
@subtitle A User's Guide for Nomad Web Browser
@author The Nomad Developers

@page
@vskip 0pt plus 1filll
Edition @value{MANUAL-VERSION} @*
@value{MANUAL-UPDATED-MONTH} @*

@insertcopying
@end titlepage

@contents

@c *********************************************************************

@node Top
@top The Nomad Browser

Nomad is an extensible, customisable, self-documenting web browser. This
manual describes how to use Nomad and some of the ways to customise it;
it corresponds to the Nomad version @value{PROG-VERSION}.

@c See 'manual-html-mono' and 'manual-html-node' in admin/admin.el.
@html
The homepage for Nomad is at
<a href="@value{NOMAD-HOMEPAGE}">Nongnu.org</a>.<br>
To view this manual in other formats, see
<a href="@value{NOMAD-ONLINE-MANUALS}">Online Manuals</a>.<br>
@end html

For information on the extension language for Nomad, see @ref{Top, Guile
Reference Manual,, guile,}.

For information on Emacsy library used in Nomad, see @ref{Top, Emacsy,,
emacsy,}.

This is the Nomad User Manual for the Nomad Web Browser,
@value{MANUAL-VERSION}.@refill

@insertcopying

@menu
* Distribution::        Get the source code
* Installation::        Install Nomad using Guix
* Usage::               Using Nomad from the command line, application keybinds
* API::                 The programming interface
* Extensions::          Modules and extensions for Nomad
* Development::         Making changes to the source code and contributing
* Copying::             The GNU General Public License gives you permission to redistribute Nomad
* Documentation License::      The license for this documentation

@end menu

@c *********************************************************************
@node Distribution
@chapter Distribution

Nomad is @dfn{free software}; this means that everyone is free to use it
and free to redistribute it under certain conditions.  Nomad is not in
the public domain; it is copyrighted and there are restrictions on its
distribution. The precise conditions are found in the GNU General Public
License that comes with Nomad. @footnote{This manual is itself covered by
the GNU Free Documentation License.  This license is similar in spirit
to the General Public License, but is more suitable for documentation.}

Get the latest source code using git from Nongnu.org
@example
git clone @value{NOMAD-SOURCE-GIT}
@end example

@ifnothtml
The list of releases are available at @value{NOMAD-RELEASES}
@end ifnothtml

@ifhtml
@html
The list of releases are available at <a href="@value{NOMAD-RELEASES}">Releases.</a>
@end html
@end ifhtml

@c *********************************************************************
@node Installation
@chapter Installation

If you use the Gnu Guix package manager, then you can easily install
Nomad with
@example
guix package -i nomad 
@end example

If you want the latest package, clone the source repository
@example
git clone @value{NOMAD-SOURCE-GIT}
cd nomad
guix package -f ./guix.scm
@end example

@c *********************************************************************
@node Usage
@chapter Usage

@section Command-line

Nomad doesn't yet support the full set of command line options. However,
It can be run from a shell by typing

@example
nomad
@end example

@section Keybinds

Nomad intends to support Emacs-like keybinds because it's design was
inspired from Emacs. However there is no limitation on what Keybindings
Nomad can support. Nomad has the concept of key-maps just like Emacs and
users should be able to define their own keymaps.

At the top level you might want to use `M-x` (Meta/Alt X) to use the
execute command menu.

In a Webview buffer the `webview-mode-map` is active which contains the
following keybinds.

@multitable {aaaaaaaaaa} {aaaaaaaaaaaaa}
@headitem Key stroke
@tab Command
@item "C-b"
@tab (next-buffer)
@item "C-u"
@tab (back)
@item "C-m"
@tab (forward)
@item "C-n"
@tab (scroll-down)
@item "C-f"
@tab (hints)
@item "C-p"
@tab (scroll-up)
@item "C-r"
@tab (reload)
@end multitable

In Nomad's Ibuffer menu the `ctrl-x-map` is active which has these
keybindings.

@multitable {aaaaaaaaaa} {aaaaaaaaaaaaa}
@headitem Key stroke
@tab Command
@item "b"
@tab (next-buffer)
@item "k"
@tab (kill-buffer)
@end multitable

@c *********************************************************************
@node API
@chapter API

@c *********************************************************************
@node Extensions
@chapter Extensions

You can customize nomad by writing your configurations to `~/.nomad`,
which is just a scheme file!

Examples
@example
(set! search-provider-format "https://google.ca/search?q=~a")
@end example

@c *********************************************************************
@node Development
@chapter Development

In Ubuntu 19.04, the the following snippet will install most
dependencies.
@example
sudo apt install -y \
guile-2.2 \
guile-2.2-dev \
guile-library \
libgtk-3-dev \
libwebkit2gtk-4.0-dev \
libgtksourceview-4-dev
@end example

Using Guix, the following snippet will install all required dependencies
in a temporary shell.
@example
guix environment -l ./guix.scm
@end example

Then build the package with
@example
autoreconf -vif
./configure
make
@end example

@section Run from Source

Once you've built Nomad without errors, to run Nomad from the local
build.
@example
make test
./pre-inst-env ./nomad
@end example

@node Copying
@appendix GNU GENERAL PUBLIC LICENSE
@include gpl.texi

@node Documentation License
@appendix GNU Free Documentation License
@include doclicense.texi
@bye
