#!/bin/bash

export PATH="$HOME/.guix-profile/bin${PATH:+:}$PATH"
export QMAKEPATH="$HOME/.guix-profile/lib/qt5${QMAKEPATH:+:}$QMAKEPATH"
export QML2_IMPORT_PATH="$HOME/.guix-profile/lib/qt5/qml${QML2_IMPORT_PATH:+:}$QML2_IMPORT_PATH"
export QT_PLUGIN_PATH="$HOME/.guix-profile/lib/qt5/plugins${QT_PLUGIN_PATH:+:}$QT_PLUGIN_PATH"
export XDG_DATA_DIRS="$HOME/.guix-profile/share${XDG_DATA_DIRS:+:}$XDG_DATA_DIRS"
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
export GUILE_LOAD_PATH="$HOME/.guix-profile/share/guile/site/2.2${GUILE_LOAD_PATH:+:}$GUILE_LOAD_PATH"
export GUILE_LOAD_COMPILED_PATH="$HOME/.guix-profile/lib/guile/2.2/site-ccache${GUILE_LOAD_COMPILED_PATH:+:}$GUILE_LOAD_COMPILED_PATH"
export QTWEBENGINEPROCESS_PATH=/gnu/store/a7pbqhdafrkxb7zr0dclcscikp9xmxyi-qtwebengine-5.11.3/lib/qt5/libexec/QtWebEngineProcess

$HOME/.config/guix/current/bin/guix package \
				    --substitute-urls="http://216.250.119.249:8181 https://ci.guix.info" \
				    -f contrib/guix/guix.scm

$HOME/.guix-profile/bin/nomad
