* Installation
** Guix
*** Installing with Guix
#+begin_src shell
guix install nomad
#+end_src
*** Developing with Git
**** Clone the Nomad source repository
#+begin_src shell
git clone https://git.savannah.gnu.org/git/nomad.git
cd nomad
#+end_src
**** Create a Nomad environment
#+begin_src shell
guix environment -L ./guix nomad-git
#+end_src
**** Bootstrap Autotools
#+begin_src shell
./autogen.sh
#+end_src
**** Build and Run development Nomad
#+begin_src shell
./configure
make -j(nproc)
make run
#+end_src
* Run Nomad
** From the command line
Nomad doesn't yet support the full set of command line options. However, It
can be run from a shell by typing

#+begin_src shell
nomad
#+end_src

** Keybinds
Nomad intends to support Emacs-like keybinds because it's design was inspired
from Emacs. However there is no limitation on what Keybindings Nomad can
support. Nomad has the concept of key-maps just like Emacs and users should be
able to define their own keymaps.

At the top level you might want to use `M-x` (Meta/Alt X) to use the execute
command menu.

In a Webview buffer the `webview-mode-map` is active which contains the
following keybinds.

   |------------+---------------|
   | Key stroke | Command       |
   |------------+---------------|
   | "C-b"      | (next-buffer) |
   | "C-u"      | (back)        |
   | "C-m"      | (forward)     |
   | "C-n"      | (scroll-down) |
   | "C-f"      | (hints)       |
   | "C-p"      | (scroll-up)   |
   | "C-r"      | (reload)      |
   |------------+---------------|

In Nomad's Ibuffer menu the `ctrl-x-map` is active which has these
keybindings.

   |------------+---------------|
   | Key stroke | Command       |
   |------------+---------------|
   | "b"        | (next-buffer) |
   | "k"        | (kill-buffer) |
   |------------+---------------|

* Extend Nomad
You can customize nomad by writing your configurations to `~/.nomad`, which is
just a scheme file!

Examples
#+begin_src schem
(set! search-provider-format "https://google.ca/search?q=~a")
#+end_src

* Build from source
In Ubuntu 19.04, the the following snippet will install most dependencies.
#+begin_src shell :results silent
sudo apt install -y \
guile-2.2 \
guile-2.2-dev \
guile-library \
libgtk-3-dev \
libwebkit2gtk-4.0-dev \
libgtksourceview-4-dev
#+end_src

Using Guix, the following snippet will install all required
dependencies in a temporary shell.
#+begin_src shell
guix environment -l ./guix.scm
#+end_src

Then build the package with
#+begin_src shell
autoreconf -vif
./configure
make
#+end_src

** Run Nomad before you've installed Nomad
Once you've built Nomad without errors, to run Nomad from the local build.
#+begin_src bash
make test
#+end_src
